# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-21 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('tag', models.CharField(blank=True, max_length=35)),
                ('recommender', models.CharField(blank=True, max_length=100)),
                ('recorder', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('tag', models.CharField(blank=True, max_length=35)),
                ('recommender', models.CharField(blank=True, max_length=100)),
                ('recorder', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('tag', models.CharField(blank=True, max_length=35)),
                ('recommender', models.CharField(blank=True, max_length=100)),
                ('recorder', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
